language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
  - secure: HpSoaFnpyI3XVO2vjYXon17Ntg3aJOxpQqIUAghWms9MoX9vL85xxcGWr6DWYacX6URhT72VgBwa023hI1I/h2/VMXdIwfwdrpr8unS8QKuQzDr9tQNTWW7htJoqPrqL21uNCd8SBBrHMnwQvbwsifccVnLlaf+l+No2+Ezs+jc=
  - secure: BP5T/ghQJS3n4xkpq2dZEYK+0RdwrCO3o9PX3qW+Kqk/AyhrpJppglwegDisbfhzCFOZpx+Tklxll6aUX55NtUdZT/sveCJu2TEIcIDF3LdWntOfeRVoq1seaALbZA3O5gL6uzcISt16zIdfa7f5DbrQ5n5n9IoXIRIAvQCbIZ0=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
before_script:
- ember sauce:connect
script:
- ember try $EMBER_TRY_SCENARIO test
after_script:
- ember sauce:disconnect
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ded8f776cc4787c57dcc
    on_success: change
    on_failure: always
    on_start: never
